### PR TITLE
Added statistics cooling, defrost, summary. 

### PR DESCRIPTION
**Pull request by asdt1803**
Added statistics:  cooling, defrost, summary. 
Bugfix: Added User-Agent to solve empty response from wemportal (see https://github.com/erikkastelec/hass-WEM-Portal/issues/51)

### CODE REVIEW

**Comment by floek** [comment]
Hi @asdt1803 ,
thanks for our merge request. The linter is not happy ;)
Best

**Comment by asdt1803** [comment]
Hi @floek , 
sorry it's the first time I try to contribute something on github. If I interpret that correctly, it's just one lines length that is complained about, right? That is fixed in my fork now.
What am I supposed to do now? Close the merge request and open another? 

Best regards

**Comment by floek** [comment]
Thank you! Contributions are very welcome. For future contribution, you could lint the code locally with pylint before pushing it to github. It should be possible to update the pull request with the updated code, but I also have to research how it works ;)

**Comment by floek** [comment]
Ah, just update the branch [asdt1803:biblock_lwp](https://github.com/asdt1803/wemportal/tree/biblock_lwp)
See: https://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review

**Comment by asdt1803** [comment]
Hi @floek ,
Thank you for your help. Lint seems to be happier now ;-)

**Pull request merged**
